import type { Metadata } from "next";
import { Fraunces } from "next/font/google";

import "./globals.css";

const Fraunce = Fraunces({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Fraunce.className}>{children}</body>
    </html>
  );
}
